[project]
name = "migrate-cursor-folder"
version = "0.1.0"
description = "Quick python script for perform migrate folder location"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.0",
    "pyarrow>=21.0.0",
    "send2trash>=1.8.3",
    "tqdm>=4.67.1",
]
